spring:
  application:
    name: sb-virtual-threads
  threads:
    virtual:
      enabled: true

# planning services
accommodation:
  service:
    url: "http://localhost:7070/sec02/accommodations/"
event:
  service:
    url: "http://localhost:7070/sec02/events/"
local-recommendation:
  service:
    url: "http://localhost:7070/sec02/local-recommendations/"
transportation:
  service:
    url: "http://localhost:7070/sec02/transportation/"
weather:
  service:
    url: "http://localhost:7070/sec02/weather/"

flight-search:
  service:
    url: "http://localhost:7070/sec03/flight/search/"
flight-reservation:
  service:
    url: "http://localhost:7070/sec03/flight/reserve/"

